// Mocks generated by Mockito 5.4.6 from annotations
// in azkar_app/test/features/azkar/data/repositories/azkar_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:azkar_app/features/azkar/data/datasources/azkar_local_data_source.dart'
    as _i2;
import 'package:azkar_app/features/azkar/data/models/azkar_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AzkarLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAzkarLocalDataSource extends _i1.Mock
    implements _i2.AzkarLocalDataSource {
  MockAzkarLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AzkarModel>> getAzkar() => (super.noSuchMethod(
        Invocation.method(
          #getAzkar,
          [],
        ),
        returnValue: _i3.Future<List<_i4.AzkarModel>>.value(<_i4.AzkarModel>[]),
      ) as _i3.Future<List<_i4.AzkarModel>>);

  @override
  _i3.Future<List<_i4.AzkarModel>> getCustomAzkar() => (super.noSuchMethod(
        Invocation.method(
          #getCustomAzkar,
          [],
        ),
        returnValue: _i3.Future<List<_i4.AzkarModel>>.value(<_i4.AzkarModel>[]),
      ) as _i3.Future<List<_i4.AzkarModel>>);

  @override
  _i3.Future<void> saveCustomAzkar(List<_i4.AzkarModel>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomAzkar,
          [items],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCustomCategory({
    required String? originalCategory,
    required String? newCategory,
    required List<_i4.AzkarModel>? items,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomCategory,
          [],
          {
            #originalCategory: originalCategory,
            #newCategory: newCategory,
            #items: items,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCustomCategory(String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomCategory,
          [categoryName],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
