// Mocks generated by Mockito 5.4.6 from annotations
// in azkar_app/test/features/quran/presentation/screens/quran_details_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:azkar_app/features/quran/domain/usecases/check_surah_downloaded_usecase.dart'
    as _i9;
import 'package:azkar_app/features/quran/domain/usecases/clear_all_saved_quran_values_usecase.dart'
    as _i6;
import 'package:azkar_app/features/quran/domain/usecases/clear_saved_position_usecase.dart'
    as _i7;
import 'package:azkar_app/features/quran/domain/usecases/get_latest_quran_surah_number_usecase.dart'
    as _i4;
import 'package:azkar_app/features/quran/domain/usecases/get_saved_quran_page_number_usecase.dart'
    as _i2;
import 'package:azkar_app/features/quran/domain/usecases/get_surah_audio_usecase.dart'
    as _i8;
import 'package:azkar_app/features/quran/domain/usecases/save_latest_quran_surah_number_usecase.dart'
    as _i5;
import 'package:azkar_app/features/quran/domain/usecases/save_quran_page_number_usecase.dart'
    as _i3;
import 'package:azkar_app/features/quran/presentation/providers/quran_provider.dart'
    as _i11;
import 'package:just_audio/just_audio.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetSavedQuranPageNumberUseCase_0 extends _i1.SmartFake
    implements _i2.GetSavedQuranPageNumberUseCase {
  _FakeGetSavedQuranPageNumberUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveQuranPageNumberUseCase_1 extends _i1.SmartFake
    implements _i3.SaveQuranPageNumberUseCase {
  _FakeSaveQuranPageNumberUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLatestQuranSurahNumberUseCase_2 extends _i1.SmartFake
    implements _i4.GetLatestQuranSurahNumberUseCase {
  _FakeGetLatestQuranSurahNumberUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveLatestQuranSurahNumberUseCase_3 extends _i1.SmartFake
    implements _i5.SaveLatestQuranSurahNumberUseCase {
  _FakeSaveLatestQuranSurahNumberUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClearAllSavedQuranValuesUseCase_4 extends _i1.SmartFake
    implements _i6.ClearAllSavedQuranValuesUseCase {
  _FakeClearAllSavedQuranValuesUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClearSavedPositionUseCase_5 extends _i1.SmartFake
    implements _i7.ClearSavedPositionUseCase {
  _FakeClearSavedPositionUseCase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSurahAudioUseCase_6 extends _i1.SmartFake
    implements _i8.GetSurahAudioUseCase {
  _FakeGetSurahAudioUseCase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckSurahDownloadedUseCase_7 extends _i1.SmartFake
    implements _i9.CheckSurahDownloadedUseCase {
  _FakeCheckSurahDownloadedUseCase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayer_8 extends _i1.SmartFake implements _i10.AudioPlayer {
  _FakeAudioPlayer_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuranProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranProvider extends _i1.Mock implements _i11.QuranProvider {
  MockQuranProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSavedQuranPageNumberUseCase get getQuranPageNumberUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getQuranPageNumberUseCase),
        returnValue: _FakeGetSavedQuranPageNumberUseCase_0(
          this,
          Invocation.getter(#getQuranPageNumberUseCase),
        ),
      ) as _i2.GetSavedQuranPageNumberUseCase);

  @override
  _i3.SaveQuranPageNumberUseCase get saveQuranPageNumberUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#saveQuranPageNumberUseCase),
        returnValue: _FakeSaveQuranPageNumberUseCase_1(
          this,
          Invocation.getter(#saveQuranPageNumberUseCase),
        ),
      ) as _i3.SaveQuranPageNumberUseCase);

  @override
  _i4.GetLatestQuranSurahNumberUseCase get getLatestSurahNumberUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getLatestSurahNumberUseCase),
        returnValue: _FakeGetLatestQuranSurahNumberUseCase_2(
          this,
          Invocation.getter(#getLatestSurahNumberUseCase),
        ),
      ) as _i4.GetLatestQuranSurahNumberUseCase);

  @override
  _i5.SaveLatestQuranSurahNumberUseCase get saveLatestSurahNumberUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#saveLatestSurahNumberUseCase),
        returnValue: _FakeSaveLatestQuranSurahNumberUseCase_3(
          this,
          Invocation.getter(#saveLatestSurahNumberUseCase),
        ),
      ) as _i5.SaveLatestQuranSurahNumberUseCase);

  @override
  _i6.ClearAllSavedQuranValuesUseCase get clearAllSavedQuranValuesUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#clearAllSavedQuranValuesUseCase),
        returnValue: _FakeClearAllSavedQuranValuesUseCase_4(
          this,
          Invocation.getter(#clearAllSavedQuranValuesUseCase),
        ),
      ) as _i6.ClearAllSavedQuranValuesUseCase);

  @override
  _i7.ClearSavedPositionUseCase get clearSavedPositionUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#clearSavedPositionUseCase),
        returnValue: _FakeClearSavedPositionUseCase_5(
          this,
          Invocation.getter(#clearSavedPositionUseCase),
        ),
      ) as _i7.ClearSavedPositionUseCase);

  @override
  _i8.GetSurahAudioUseCase get getSurahAudioUseCase => (super.noSuchMethod(
        Invocation.getter(#getSurahAudioUseCase),
        returnValue: _FakeGetSurahAudioUseCase_6(
          this,
          Invocation.getter(#getSurahAudioUseCase),
        ),
      ) as _i8.GetSurahAudioUseCase);

  @override
  _i9.CheckSurahDownloadedUseCase get checkSurahDownloadedUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#checkSurahDownloadedUseCase),
        returnValue: _FakeCheckSurahDownloadedUseCase_7(
          this,
          Invocation.getter(#checkSurahDownloadedUseCase),
        ),
      ) as _i9.CheckSurahDownloadedUseCase);

  @override
  _i10.AudioPlayer get player => (super.noSuchMethod(
        Invocation.getter(#player),
        returnValue: _FakeAudioPlayer_8(
          this,
          Invocation.getter(#player),
        ),
      ) as _i10.AudioPlayer);

  @override
  bool get isDownloading => (super.noSuchMethod(
        Invocation.getter(#isDownloading),
        returnValue: false,
      ) as bool);

  @override
  _i12.Stream<Duration?> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i12.Stream<Duration?>.empty(),
      ) as _i12.Stream<Duration?>);

  @override
  _i12.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i12.Stream<Duration?>.empty(),
      ) as _i12.Stream<Duration?>);

  @override
  bool get isActuallyPlaying => (super.noSuchMethod(
        Invocation.getter(#isActuallyPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> loadSavedPositions() => (super.noSuchMethod(
        Invocation.method(
          #loadSavedPositions,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> saveQuranPageNumber(int? pageNumber) => (super.noSuchMethod(
        Invocation.method(
          #saveQuranPageNumber,
          [pageNumber],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> clearAllSavedQuranValues() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSavedQuranValues,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> clearSavedPosition() => (super.noSuchMethod(
        Invocation.method(
          #clearSavedPosition,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> saveLatestQuranSurahNumber(int? surahNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLatestQuranSurahNumber,
          [surahNumber],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> toggleAudio(
    int? surahNumber,
    String? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleAudio,
          [
            surahNumber,
            url,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void resetAudio() => super.noSuchMethod(
        Invocation.method(
          #resetAudio,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseForNotification() => super.noSuchMethod(
        Invocation.method(
          #pauseForNotification,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
