// Mocks generated by Mockito 5.4.6 from annotations
// in azkar_app/test/features/azkar/presentation/screens/all_azkar_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:azkar_app/core/enums/app_loading_status.dart' as _i11;
import 'package:azkar_app/core/providers/favorites_provider.dart' as _i14;
import 'package:azkar_app/features/azkar/domain/entities/zekr_entity.dart'
    as _i10;
import 'package:azkar_app/features/azkar/domain/usecases/delete_custom_azkar_usecase.dart'
    as _i5;
import 'package:azkar_app/features/azkar/domain/usecases/get_azkar_usecase.dart'
    as _i2;
import 'package:azkar_app/features/azkar/domain/usecases/get_custom_azkar_usecase.dart'
    as _i3;
import 'package:azkar_app/features/azkar/domain/usecases/save_custom_azkar_usecase.dart'
    as _i4;
import 'package:azkar_app/features/azkar/domain/usecases/update_custom_azkar_usecase.dart'
    as _i6;
import 'package:azkar_app/features/azkar/presentation/providers/azkar_provider.dart'
    as _i9;
import 'package:azkar_app/features/surah/domain/entities/surah_entity.dart'
    as _i16;
import 'package:azkar_app/features/surah/domain/usecases/get_surah_usecase.dart'
    as _i8;
import 'package:azkar_app/features/surah/presentation/providers/surah_provider.dart'
    as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAzkarUseCase_0 extends _i1.SmartFake
    implements _i2.GetAzkarUseCase {
  _FakeGetAzkarUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetCustomAzkarUseCase_1 extends _i1.SmartFake
    implements _i3.GetCustomAzkarUseCase {
  _FakeGetCustomAzkarUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveCustomAzkarUseCase_2 extends _i1.SmartFake
    implements _i4.SaveCustomAzkarUseCase {
  _FakeSaveCustomAzkarUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteCustomAzkarUseCase_3 extends _i1.SmartFake
    implements _i5.DeleteCustomAzkarUseCase {
  _FakeDeleteCustomAzkarUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCustomAzkarUseCase_4 extends _i1.SmartFake
    implements _i6.UpdateCustomAzkarUseCase {
  _FakeUpdateCustomAzkarUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_5 extends _i1.SmartFake
    implements _i7.SharedPreferences {
  _FakeSharedPreferences_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSurahUseCase_6 extends _i1.SmartFake
    implements _i8.GetSurahUseCase {
  _FakeGetSurahUseCase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AzkarProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAzkarProvider extends _i1.Mock implements _i9.AzkarProvider {
  MockAzkarProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAzkarUseCase get getAzkarUseCase => (super.noSuchMethod(
        Invocation.getter(#getAzkarUseCase),
        returnValue: _FakeGetAzkarUseCase_0(
          this,
          Invocation.getter(#getAzkarUseCase),
        ),
      ) as _i2.GetAzkarUseCase);

  @override
  _i3.GetCustomAzkarUseCase get getCustomAzkarUseCase => (super.noSuchMethod(
        Invocation.getter(#getCustomAzkarUseCase),
        returnValue: _FakeGetCustomAzkarUseCase_1(
          this,
          Invocation.getter(#getCustomAzkarUseCase),
        ),
      ) as _i3.GetCustomAzkarUseCase);

  @override
  _i4.SaveCustomAzkarUseCase get saveCustomAzkarUseCase => (super.noSuchMethod(
        Invocation.getter(#saveCustomAzkarUseCase),
        returnValue: _FakeSaveCustomAzkarUseCase_2(
          this,
          Invocation.getter(#saveCustomAzkarUseCase),
        ),
      ) as _i4.SaveCustomAzkarUseCase);

  @override
  _i5.DeleteCustomAzkarUseCase get deleteCustomAzkarUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#deleteCustomAzkarUseCase),
        returnValue: _FakeDeleteCustomAzkarUseCase_3(
          this,
          Invocation.getter(#deleteCustomAzkarUseCase),
        ),
      ) as _i5.DeleteCustomAzkarUseCase);

  @override
  _i6.UpdateCustomAzkarUseCase get updateCustomAzkarUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#updateCustomAzkarUseCase),
        returnValue: _FakeUpdateCustomAzkarUseCase_4(
          this,
          Invocation.getter(#updateCustomAzkarUseCase),
        ),
      ) as _i6.UpdateCustomAzkarUseCase);

  @override
  List<_i10.ZekrEntity> get azkarList => (super.noSuchMethod(
        Invocation.getter(#azkarList),
        returnValue: <_i10.ZekrEntity>[],
      ) as List<_i10.ZekrEntity>);

  @override
  _i11.AppLoadingStatus get azkarStatus => (super.noSuchMethod(
        Invocation.getter(#azkarStatus),
        returnValue: _i11.AppLoadingStatus.initial,
      ) as _i11.AppLoadingStatus);

  @override
  List<_i10.ZekrEntity> get customAzkarList => (super.noSuchMethod(
        Invocation.getter(#customAzkarList),
        returnValue: <_i10.ZekrEntity>[],
      ) as List<_i10.ZekrEntity>);

  @override
  List<String> get customCategories => (super.noSuchMethod(
        Invocation.getter(#customCategories),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get allCategories => (super.noSuchMethod(
        Invocation.getter(#allCategories),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, int> get categoryCounts => (super.noSuchMethod(
        Invocation.getter(#categoryCounts),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> loadAzkar() => (super.noSuchMethod(
        Invocation.method(
          #loadAzkar,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadCustomAzkar() => (super.noSuchMethod(
        Invocation.method(
          #loadCustomAzkar,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> saveCustomAzkarCategory({
    required String? categoryTitle,
    required List<Map<String, dynamic>>? azkarItems,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomAzkarCategory,
          [],
          {
            #categoryTitle: categoryTitle,
            #azkarItems: azkarItems,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateCustomAzkarCategory({
    required String? originalCategory,
    required String? categoryTitle,
    required List<Map<String, dynamic>>? azkarItems,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomAzkarCategory,
          [],
          {
            #originalCategory: originalCategory,
            #categoryTitle: categoryTitle,
            #azkarItems: azkarItems,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteCustomCategory(String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomCategory,
          [categoryName],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FavoritesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesProvider extends _i1.Mock implements _i14.FavoritesProvider {
  MockFavoritesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_5(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i7.SharedPreferences);

  @override
  List<String> get favCategories => (super.noSuchMethod(
        Invocation.getter(#favCategories),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get favIndividualItems => (super.noSuchMethod(
        Invocation.getter(#favIndividualItems),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> loadFavorites() => (super.noSuchMethod(
        Invocation.method(
          #loadFavorites,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> toggleCategoryFavorite(String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleCategoryFavorite,
          [categoryName],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> toggleItemFavorite(String? itemIdentifier) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleItemFavorite,
          [itemIdentifier],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  bool isCategoryFav(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isCategoryFav,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isItemFav(String? identifier) => (super.noSuchMethod(
        Invocation.method(
          #isItemFav,
          [identifier],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> renameCategory(
    String? oldName,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameCategory,
          [
            oldName,
            newName,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SurahProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurahProvider extends _i1.Mock implements _i15.SurahProvider {
  MockSurahProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetSurahUseCase get getSurahUseCase => (super.noSuchMethod(
        Invocation.getter(#getSurahUseCase),
        returnValue: _FakeGetSurahUseCase_6(
          this,
          Invocation.getter(#getSurahUseCase),
        ),
      ) as _i8.GetSurahUseCase);

  @override
  List<_i16.SurahEntity> get surahList => (super.noSuchMethod(
        Invocation.getter(#surahList),
        returnValue: <_i16.SurahEntity>[],
      ) as List<_i16.SurahEntity>);

  @override
  _i11.AppLoadingStatus get surahStatus => (super.noSuchMethod(
        Invocation.getter(#surahStatus),
        returnValue: _i11.AppLoadingStatus.initial,
      ) as _i11.AppLoadingStatus);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> loadSurah() => (super.noSuchMethod(
        Invocation.method(
          #loadSurah,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
