// Mocks generated by Mockito 5.4.6 from annotations
// in azkar_app/test/features/azkar/presentation/providers/azkar_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:azkar_app/core/error/failures.dart' as _i6;
import 'package:azkar_app/core/usecases/usecase.dart' as _i8;
import 'package:azkar_app/features/azkar/domain/entities/zekr_entity.dart'
    as _i7;
import 'package:azkar_app/features/azkar/domain/repositories/azkar_repository.dart'
    as _i2;
import 'package:azkar_app/features/azkar/domain/usecases/delete_custom_azkar_usecase.dart'
    as _i11;
import 'package:azkar_app/features/azkar/domain/usecases/get_azkar_usecase.dart'
    as _i4;
import 'package:azkar_app/features/azkar/domain/usecases/get_custom_azkar_usecase.dart'
    as _i9;
import 'package:azkar_app/features/azkar/domain/usecases/save_custom_azkar_usecase.dart'
    as _i10;
import 'package:azkar_app/features/azkar/domain/usecases/update_custom_azkar_usecase.dart'
    as _i12;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAzkarRepository_0 extends _i1.SmartFake
    implements _i2.AzkarRepository {
  _FakeAzkarRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAzkarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAzkarUseCase extends _i1.Mock implements _i4.GetAzkarUseCase {
  MockGetAzkarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AzkarRepository get azkarRepository => (super.noSuchMethod(
        Invocation.getter(#azkarRepository),
        returnValue: _FakeAzkarRepository_0(
          this,
          Invocation.getter(#azkarRepository),
        ),
      ) as _i2.AzkarRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ZekrEntity>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.ZekrEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.ZekrEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ZekrEntity>>>);
}

/// A class which mocks [GetCustomAzkarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCustomAzkarUseCase extends _i1.Mock
    implements _i9.GetCustomAzkarUseCase {
  MockGetCustomAzkarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AzkarRepository get azkarRepository => (super.noSuchMethod(
        Invocation.getter(#azkarRepository),
        returnValue: _FakeAzkarRepository_0(
          this,
          Invocation.getter(#azkarRepository),
        ),
      ) as _i2.AzkarRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ZekrEntity>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.ZekrEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.ZekrEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ZekrEntity>>>);
}

/// A class which mocks [SaveCustomAzkarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveCustomAzkarUseCase extends _i1.Mock
    implements _i10.SaveCustomAzkarUseCase {
  MockSaveCustomAzkarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AzkarRepository get azkarRepository => (super.noSuchMethod(
        Invocation.getter(#azkarRepository),
        returnValue: _FakeAzkarRepository_0(
          this,
          Invocation.getter(#azkarRepository),
        ),
      ) as _i2.AzkarRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          List<_i7.ZekrEntity>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteCustomAzkarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCustomAzkarUseCase extends _i1.Mock
    implements _i11.DeleteCustomAzkarUseCase {
  MockDeleteCustomAzkarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AzkarRepository get azkarRepository => (super.noSuchMethod(
        Invocation.getter(#azkarRepository),
        returnValue: _FakeAzkarRepository_0(
          this,
          Invocation.getter(#azkarRepository),
        ),
      ) as _i2.AzkarRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UpdateCustomAzkarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCustomAzkarUseCase extends _i1.Mock
    implements _i12.UpdateCustomAzkarUseCase {
  MockUpdateCustomAzkarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AzkarRepository get azkarRepository => (super.noSuchMethod(
        Invocation.getter(#azkarRepository),
        returnValue: _FakeAzkarRepository_0(
          this,
          Invocation.getter(#azkarRepository),
        ),
      ) as _i2.AzkarRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i12.UpdateCustomAzkarParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
