// Mocks generated by Mockito 5.4.6 from annotations
// in azkar_app/test/features/home/presentation/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:azkar_app/core/enums/app_loading_status.dart' as _i12;
import 'package:azkar_app/core/models/city.dart' as _i17;
import 'package:azkar_app/core/providers/favorites_provider.dart' as _i20;
import 'package:azkar_app/core/providers/notification_provider.dart' as _i22;
import 'package:azkar_app/core/providers/theme_provider.dart' as _i21;
import 'package:azkar_app/core/services/prayer_times_service.dart' as _i7;
import 'package:azkar_app/features/azkar/domain/entities/zekr_entity.dart'
    as _i11;
import 'package:azkar_app/features/azkar/domain/usecases/delete_custom_azkar_usecase.dart'
    as _i5;
import 'package:azkar_app/features/azkar/domain/usecases/get_azkar_usecase.dart'
    as _i2;
import 'package:azkar_app/features/azkar/domain/usecases/get_custom_azkar_usecase.dart'
    as _i3;
import 'package:azkar_app/features/azkar/domain/usecases/save_custom_azkar_usecase.dart'
    as _i4;
import 'package:azkar_app/features/azkar/domain/usecases/update_custom_azkar_usecase.dart'
    as _i6;
import 'package:azkar_app/features/azkar/presentation/providers/azkar_provider.dart'
    as _i10;
import 'package:azkar_app/features/names_of_allah/domain/entities/names_of_allah_entity.dart'
    as _i19;
import 'package:azkar_app/features/names_of_allah/domain/usecases/get_names_of_allah_usecase.dart'
    as _i9;
import 'package:azkar_app/features/names_of_allah/presentation/providers/names_of_allah_provider.dart'
    as _i18;
import 'package:azkar_app/features/prayer_times/presentation/providers/prayer_times_provider.dart'
    as _i15;
import 'package:azkar_app/features/tasbeh/presentation/providers/tasbeh_provider.dart'
    as _i23;
import 'package:flutter/material.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAzkarUseCase_0 extends _i1.SmartFake
    implements _i2.GetAzkarUseCase {
  _FakeGetAzkarUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetCustomAzkarUseCase_1 extends _i1.SmartFake
    implements _i3.GetCustomAzkarUseCase {
  _FakeGetCustomAzkarUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveCustomAzkarUseCase_2 extends _i1.SmartFake
    implements _i4.SaveCustomAzkarUseCase {
  _FakeSaveCustomAzkarUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteCustomAzkarUseCase_3 extends _i1.SmartFake
    implements _i5.DeleteCustomAzkarUseCase {
  _FakeDeleteCustomAzkarUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCustomAzkarUseCase_4 extends _i1.SmartFake
    implements _i6.UpdateCustomAzkarUseCase {
  _FakeUpdateCustomAzkarUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrayerTimeService_5 extends _i1.SmartFake
    implements _i7.PrayerTimeService {
  _FakePrayerTimeService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_6 extends _i1.SmartFake
    implements _i8.SharedPreferences {
  _FakeSharedPreferences_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetNamesOfAllahUseCase_7 extends _i1.SmartFake
    implements _i9.GetNamesOfAllahUseCase {
  _FakeGetNamesOfAllahUseCase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AzkarProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAzkarProvider extends _i1.Mock implements _i10.AzkarProvider {
  MockAzkarProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAzkarUseCase get getAzkarUseCase => (super.noSuchMethod(
        Invocation.getter(#getAzkarUseCase),
        returnValue: _FakeGetAzkarUseCase_0(
          this,
          Invocation.getter(#getAzkarUseCase),
        ),
      ) as _i2.GetAzkarUseCase);

  @override
  _i3.GetCustomAzkarUseCase get getCustomAzkarUseCase => (super.noSuchMethod(
        Invocation.getter(#getCustomAzkarUseCase),
        returnValue: _FakeGetCustomAzkarUseCase_1(
          this,
          Invocation.getter(#getCustomAzkarUseCase),
        ),
      ) as _i3.GetCustomAzkarUseCase);

  @override
  _i4.SaveCustomAzkarUseCase get saveCustomAzkarUseCase => (super.noSuchMethod(
        Invocation.getter(#saveCustomAzkarUseCase),
        returnValue: _FakeSaveCustomAzkarUseCase_2(
          this,
          Invocation.getter(#saveCustomAzkarUseCase),
        ),
      ) as _i4.SaveCustomAzkarUseCase);

  @override
  _i5.DeleteCustomAzkarUseCase get deleteCustomAzkarUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#deleteCustomAzkarUseCase),
        returnValue: _FakeDeleteCustomAzkarUseCase_3(
          this,
          Invocation.getter(#deleteCustomAzkarUseCase),
        ),
      ) as _i5.DeleteCustomAzkarUseCase);

  @override
  _i6.UpdateCustomAzkarUseCase get updateCustomAzkarUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#updateCustomAzkarUseCase),
        returnValue: _FakeUpdateCustomAzkarUseCase_4(
          this,
          Invocation.getter(#updateCustomAzkarUseCase),
        ),
      ) as _i6.UpdateCustomAzkarUseCase);

  @override
  List<_i11.ZekrEntity> get azkarList => (super.noSuchMethod(
        Invocation.getter(#azkarList),
        returnValue: <_i11.ZekrEntity>[],
      ) as List<_i11.ZekrEntity>);

  @override
  _i12.AppLoadingStatus get azkarStatus => (super.noSuchMethod(
        Invocation.getter(#azkarStatus),
        returnValue: _i12.AppLoadingStatus.initial,
      ) as _i12.AppLoadingStatus);

  @override
  List<_i11.ZekrEntity> get customAzkarList => (super.noSuchMethod(
        Invocation.getter(#customAzkarList),
        returnValue: <_i11.ZekrEntity>[],
      ) as List<_i11.ZekrEntity>);

  @override
  List<String> get customCategories => (super.noSuchMethod(
        Invocation.getter(#customCategories),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get allCategories => (super.noSuchMethod(
        Invocation.getter(#allCategories),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, int> get categoryCounts => (super.noSuchMethod(
        Invocation.getter(#categoryCounts),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> loadAzkar() => (super.noSuchMethod(
        Invocation.method(
          #loadAzkar,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> loadCustomAzkar() => (super.noSuchMethod(
        Invocation.method(
          #loadCustomAzkar,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveCustomAzkarCategory({
    required String? categoryTitle,
    required List<Map<String, dynamic>>? azkarItems,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomAzkarCategory,
          [],
          {
            #categoryTitle: categoryTitle,
            #azkarItems: azkarItems,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> updateCustomAzkarCategory({
    required String? originalCategory,
    required String? categoryTitle,
    required List<Map<String, dynamic>>? azkarItems,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomAzkarCategory,
          [],
          {
            #originalCategory: originalCategory,
            #categoryTitle: categoryTitle,
            #azkarItems: azkarItems,
          },
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> deleteCustomCategory(String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomCategory,
          [categoryName],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PrayerTimesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerTimesProvider extends _i1.Mock
    implements _i15.PrayerTimesProvider {
  MockPrayerTimesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.PrayerTimeService get prayerTimeService => (super.noSuchMethod(
        Invocation.getter(#prayerTimeService),
        returnValue: _FakePrayerTimeService_5(
          this,
          Invocation.getter(#prayerTimeService),
        ),
      ) as _i7.PrayerTimeService);

  @override
  _i8.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_6(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i8.SharedPreferences);

  @override
  bool get isAutoLocation => (super.noSuchMethod(
        Invocation.getter(#isAutoLocation),
        returnValue: false,
      ) as bool);

  @override
  bool get hasAnyOverrides => (super.noSuchMethod(
        Invocation.getter(#hasAnyOverrides),
        returnValue: false,
      ) as bool);

  @override
  Map<String, _i16.TimeOfDay> get allDisplayTimes => (super.noSuchMethod(
        Invocation.getter(#allDisplayTimes),
        returnValue: <String, _i16.TimeOfDay>{},
      ) as Map<String, _i16.TimeOfDay>);

  @override
  set onOverrideChanged(_i14.VoidCallback? value) => super.noSuchMethod(
        Invocation.setter(
          #onOverrideChanged,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> loadPrayerTimes({bool? forceRecalc = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPrayerTimes,
          [],
          {#forceRecalc: forceRecalc},
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<bool> selectCity(_i17.City? city) => (super.noSuchMethod(
        Invocation.method(
          #selectCity,
          [city],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i16.TimeOfDay? getDisplayTime(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getDisplayTime,
        [key],
      )) as _i16.TimeOfDay?);

  @override
  bool isOverridden(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isOverridden,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setOverride(
    String? key,
    _i16.TimeOfDay? time,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setOverride,
          [
            key,
            time,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearOverride(String? key) => super.noSuchMethod(
        Invocation.method(
          #clearOverride,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllOverrides() => super.noSuchMethod(
        Invocation.method(
          #clearAllOverrides,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NamesOfAllahProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNamesOfAllahProvider extends _i1.Mock
    implements _i18.NamesOfAllahProvider {
  MockNamesOfAllahProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.GetNamesOfAllahUseCase get getNamesOfAllahUseCase => (super.noSuchMethod(
        Invocation.getter(#getNamesOfAllahUseCase),
        returnValue: _FakeGetNamesOfAllahUseCase_7(
          this,
          Invocation.getter(#getNamesOfAllahUseCase),
        ),
      ) as _i9.GetNamesOfAllahUseCase);

  @override
  List<_i19.NamesOfAllahEntity> get namesOfAllahList => (super.noSuchMethod(
        Invocation.getter(#namesOfAllahList),
        returnValue: <_i19.NamesOfAllahEntity>[],
      ) as List<_i19.NamesOfAllahEntity>);

  @override
  _i12.AppLoadingStatus get namesOfAllahStatus => (super.noSuchMethod(
        Invocation.getter(#namesOfAllahStatus),
        returnValue: _i12.AppLoadingStatus.initial,
      ) as _i12.AppLoadingStatus);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> loadNamesOfAllah() => (super.noSuchMethod(
        Invocation.method(
          #loadNamesOfAllah,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FavoritesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesProvider extends _i1.Mock implements _i20.FavoritesProvider {
  MockFavoritesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_6(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i8.SharedPreferences);

  @override
  List<String> get favCategories => (super.noSuchMethod(
        Invocation.getter(#favCategories),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get favIndividualItems => (super.noSuchMethod(
        Invocation.getter(#favIndividualItems),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> loadFavorites() => (super.noSuchMethod(
        Invocation.method(
          #loadFavorites,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> toggleCategoryFavorite(String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleCategoryFavorite,
          [categoryName],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> toggleItemFavorite(String? itemIdentifier) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleItemFavorite,
          [itemIdentifier],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  bool isCategoryFav(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isCategoryFav,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isItemFav(String? identifier) => (super.noSuchMethod(
        Invocation.method(
          #isItemFav,
          [identifier],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> renameCategory(
    String? oldName,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameCategory,
          [
            oldName,
            newName,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i21.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SharedPreferences get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: _FakeSharedPreferences_6(
          this,
          Invocation.getter(#prefs),
        ),
      ) as _i8.SharedPreferences);

  @override
  _i16.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i16.ThemeMode.system,
      ) as _i16.ThemeMode);

  @override
  double get textScaleFactor => (super.noSuchMethod(
        Invocation.getter(#textScaleFactor),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isLight => (super.noSuchMethod(
        Invocation.getter(#isLight),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> loadTheme() => (super.noSuchMethod(
        Invocation.method(
          #loadTheme,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void setThemeMode(_i16.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cycleThemeMode() => super.noSuchMethod(
        Invocation.method(
          #cycleThemeMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTextScaleFactor(double? newFactor) => super.noSuchMethod(
        Invocation.method(
          #setTextScaleFactor,
          [newFactor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationProvider extends _i1.Mock
    implements _i22.NotificationProvider {
  MockNotificationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get areNotificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#areNotificationsEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isPrayerAdhanEnabled => (super.noSuchMethod(
        Invocation.getter(#isPrayerAdhanEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isMorningEveningAzkarEnabled => (super.noSuchMethod(
        Invocation.getter(#isMorningEveningAzkarEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isPeriodicAzkarEnabled => (super.noSuchMethod(
        Invocation.getter(#isPeriodicAzkarEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isPreAdhanEnabled => (super.noSuchMethod(
        Invocation.getter(#isPreAdhanEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isQuranAfterSalahEnabled => (super.noSuchMethod(
        Invocation.getter(#isQuranAfterSalahEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isProphetBlessingsEnabled => (super.noSuchMethod(
        Invocation.getter(#isProphetBlessingsEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<String?> toggleAllNotifications(bool? newValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleAllNotifications,
          [newValue],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);

  @override
  _i13.Future<void> toggleNotificationType(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleNotificationType,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> refreshNotifications() => (super.noSuchMethod(
        Invocation.method(
          #refreshNotifications,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> applyNotificationStates() => (super.noSuchMethod(
        Invocation.method(
          #applyNotificationStates,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TasbehProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasbehProvider extends _i1.Mock implements _i23.TasbehProvider {
  MockTasbehProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_6(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i8.SharedPreferences);

  @override
  int get count => (super.noSuchMethod(
        Invocation.getter(#count),
        returnValue: 0,
      ) as int);

  @override
  int get savedCount => (super.noSuchMethod(
        Invocation.getter(#savedCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.Future<void> loadCount() => (super.noSuchMethod(
        Invocation.method(
          #loadCount,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> addCount() => (super.noSuchMethod(
        Invocation.method(
          #addCount,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> resetAll() => (super.noSuchMethod(
        Invocation.method(
          #resetAll,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
