import 'package:adhan_dart/adhan_dart.dart';

/// A selectable city with its geolocation, used to compute prayer times.
///
/// [region] determines both the grouping order (Arabic countries first via
/// the `ar` region) and the section header shown in the picker. [method] is
/// the calculation method appropriate for the city's country. Extend freely.
class AppCity {
  const AppCity({
    required this.name,
    required this.country,
    required this.region,
    required this.latitude,
    required this.longitude,
    required this.method,
    required this.timezone,
  });

  final String name;
  final String country;
  final String region;
  final double latitude;
  final double longitude;
  final CalculationMethod method;

  /// IANA timezone of the city, used to localize prayer times (DST-aware).
  final String timezone;
}

/// Region -> Arabic header. Order in this map (and in [appCities]) controls
/// how sections are displayed: Arabic countries first, then the rest.
const Map<String, String> regionHeaders = {
  'ar': 'الدول العربية',
  'asia': 'آسيا',
  'europe': 'أوروبا',
  'africa': 'أفريقيا',
  'americas': 'الأمريكتان',
  'oceania': 'أوقيانوسيا',
};

/// Curated list of cities from across the world, grouped so Arabic countries
/// appear at the top. Coordinates are in decimal degrees (WGS84).
const List<AppCity> appCities = [
  // ---------- الدول العربية ----------
  // مصر
  AppCity(
    name: 'القاهرة',
    country: 'مصر',
    region: 'ar',
    latitude: 30.0444,
    longitude: 31.2357,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الإسكندرية',
    country: 'مصر',
    region: 'ar',
    latitude: 31.2001,
    longitude: 29.9187,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الجيزة',
    country: 'مصر',
    region: 'ar',
    latitude: 30.0131,
    longitude: 31.2089,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الفيوم',
    country: 'مصر',
    region: 'ar',
    latitude: 29.3099,
    longitude: 30.8425,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'المنيا',
    country: 'مصر',
    region: 'ar',
    latitude: 28.1099,
    longitude: 30.7503,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'أسيوط',
    country: 'مصر',
    region: 'ar',
    latitude: 27.1783,
    longitude: 31.1859,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'سوهاج',
    country: 'مصر',
    region: 'ar',
    latitude: 26.557,
    longitude: 31.6948,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الأقصر',
    country: 'مصر',
    region: 'ar',
    latitude: 25.6872,
    longitude: 32.6396,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'أسوان',
    country: 'مصر',
    region: 'ar',
    latitude: 24.0889,
    longitude: 32.8998,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'بورسعيد',
    country: 'مصر',
    region: 'ar',
    latitude: 31.2565,
    longitude: 32.2841,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الإسماعيلية',
    country: 'مصر',
    region: 'ar',
    latitude: 30.5965,
    longitude: 32.2715,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'السويس',
    country: 'مصر',
    region: 'ar',
    latitude: 29.9668,
    longitude: 32.5498,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'دمياط',
    country: 'مصر',
    region: 'ar',
    latitude: 31.4165,
    longitude: 31.8133,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'المنصورة',
    country: 'مصر',
    region: 'ar',
    latitude: 31.0409,
    longitude: 31.3785,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'طنطا',
    country: 'مصر',
    region: 'ar',
    latitude: 30.7865,
    longitude: 31.0004,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الزقازيق',
    country: 'مصر',
    region: 'ar',
    latitude: 30.5835,
    longitude: 31.5025,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'بنها',
    country: 'مصر',
    region: 'ar',
    latitude: 30.4596,
    longitude: 31.183,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'كفر الشيخ',
    country: 'مصر',
    region: 'ar',
    latitude: 31.1069,
    longitude: 30.9556,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'مرسى مطروح',
    country: 'مصر',
    region: 'ar',
    latitude: 31.3543,
    longitude: 27.2373,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'الغردقة',
    country: 'مصر',
    region: 'ar',
    latitude: 27.2579,
    longitude: 33.8116,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  AppCity(
    name: 'شرم الشيخ',
    country: 'مصر',
    region: 'ar',
    latitude: 27.9158,
    longitude: 34.33,
    method: CalculationMethod.egyptian,
    timezone: 'Africa/Cairo',
  ),
  // السعودية
  AppCity(
    name: 'الرياض',
    country: 'السعودية',
    region: 'ar',
    latitude: 24.7136,
    longitude: 46.6753,
    method: CalculationMethod.ummAlQura,
    timezone: 'Asia/Riyadh',
  ),
  AppCity(
    name: 'جدة',
    country: 'السعودية',
    region: 'ar',
    latitude: 21.4858,
    longitude: 39.1925,
    method: CalculationMethod.ummAlQura,
    timezone: 'Asia/Riyadh',
  ),
  AppCity(
    name: 'مكة المكرمة',
    country: 'السعودية',
    region: 'ar',
    latitude: 21.3891,
    longitude: 39.8579,
    method: CalculationMethod.ummAlQura,
    timezone: 'Asia/Riyadh',
  ),
  AppCity(
    name: 'المدينة المنورة',
    country: 'السعودية',
    region: 'ar',
    latitude: 24.5247,
    longitude: 39.5692,
    method: CalculationMethod.ummAlQura,
    timezone: 'Asia/Riyadh',
  ),
  AppCity(
    name: 'الدمام',
    country: 'السعودية',
    region: 'ar',
    latitude: 26.4207,
    longitude: 50.0888,
    method: CalculationMethod.ummAlQura,
    timezone: 'Asia/Riyadh',
  ),
  // الإمارات
  AppCity(
    name: 'أبوظبي',
    country: 'الإمارات',
    region: 'ar',
    latitude: 24.4539,
    longitude: 54.3773,
    method: CalculationMethod.dubai,
    timezone: 'Asia/Dubai',
  ),
  AppCity(
    name: 'دبي',
    country: 'الإمارات',
    region: 'ar',
    latitude: 25.2048,
    longitude: 55.2708,
    method: CalculationMethod.dubai,
    timezone: 'Asia/Dubai',
  ),
  AppCity(
    name: 'الشارقة',
    country: 'الإمارات',
    region: 'ar',
    latitude: 25.3463,
    longitude: 55.4209,
    method: CalculationMethod.dubai,
    timezone: 'Asia/Dubai',
  ),
  // الكويت
  AppCity(
    name: 'مدينة الكويت',
    country: 'الكويت',
    region: 'ar',
    latitude: 29.3759,
    longitude: 47.9774,
    method: CalculationMethod.kuwait,
    timezone: 'Asia/Kuwait',
  ),
  // قطر
  AppCity(
    name: 'الدوحة',
    country: 'قطر',
    region: 'ar',
    latitude: 25.2854,
    longitude: 51.531,
    method: CalculationMethod.qatar,
    timezone: 'Asia/Qatar',
  ),
  // البحرين
  AppCity(
    name: 'المنامة',
    country: 'البحرين',
    region: 'ar',
    latitude: 26.2285,
    longitude: 50.586,
    method: CalculationMethod.dubai,
    timezone: 'Asia/Bahrain',
  ),
  // عُمان
  AppCity(
    name: 'مسقط',
    country: 'عمان',
    region: 'ar',
    latitude: 23.588,
    longitude: 58.3829,
    method: CalculationMethod.ummAlQura,
    timezone: 'Asia/Muscat',
  ),
  // الأردن
  AppCity(
    name: 'عمّان',
    country: 'الأردن',
    region: 'ar',
    latitude: 31.9454,
    longitude: 35.9284,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Amman',
  ),
  // لبنان
  AppCity(
    name: 'بيروت',
    country: 'لبنان',
    region: 'ar',
    latitude: 33.8938,
    longitude: 35.5018,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Beirut',
  ),
  // سوريا
  AppCity(
    name: 'دمشق',
    country: 'سوريا',
    region: 'ar',
    latitude: 33.5138,
    longitude: 36.2765,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Damascus',
  ),
  // العراق
  AppCity(
    name: 'بغداد',
    country: 'العراق',
    region: 'ar',
    latitude: 33.3152,
    longitude: 44.3661,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Baghdad',
  ),
  AppCity(
    name: 'البصرة',
    country: 'العراق',
    region: 'ar',
    latitude: 30.5085,
    longitude: 47.7804,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Baghdad',
  ),
  // فلسطين
  AppCity(
    name: 'القدس',
    country: 'فلسطين',
    region: 'ar',
    latitude: 31.7683,
    longitude: 35.2137,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Hebron',
  ),
  AppCity(
    name: 'غزة',
    country: 'فلسطين',
    region: 'ar',
    latitude: 31.5017,
    longitude: 34.4668,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Hebron',
  ),
  // اليمن
  AppCity(
    name: 'صنعاء',
    country: 'اليمن',
    region: 'ar',
    latitude: 15.3694,
    longitude: 44.191,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Aden',
  ),
  // ليبيا
  AppCity(
    name: 'طرابلس',
    country: 'ليبيا',
    region: 'ar',
    latitude: 32.8872,
    longitude: 13.1913,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Tripoli',
  ),
  AppCity(
    name: 'بنغازي',
    country: 'ليبيا',
    region: 'ar',
    latitude: 32.1167,
    longitude: 20.0667,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Tripoli',
  ),
  // تونس
  AppCity(
    name: 'تونس العاصمة',
    country: 'تونس',
    region: 'ar',
    latitude: 36.8065,
    longitude: 10.1815,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Tunis',
  ),
  AppCity(
    name: 'صفاقس',
    country: 'تونس',
    region: 'ar',
    latitude: 34.7406,
    longitude: 10.7603,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Tunis',
  ),
  // الجزائر
  AppCity(
    name: 'الجزائر العاصمة',
    country: 'الجزائر',
    region: 'ar',
    latitude: 36.7538,
    longitude: 3.0588,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Algiers',
  ),
  AppCity(
    name: 'وهران',
    country: 'الجزائر',
    region: 'ar',
    latitude: 35.6969,
    longitude: -0.6331,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Algiers',
  ),
  // المغرب
  AppCity(
    name: 'الدار البيضاء',
    country: 'المغرب',
    region: 'ar',
    latitude: 33.5731,
    longitude: -7.5898,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Casablanca',
  ),
  AppCity(
    name: 'الرباط',
    country: 'المغرب',
    region: 'ar',
    latitude: 34.0209,
    longitude: -6.8416,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Casablanca',
  ),
  AppCity(
    name: 'فاس',
    country: 'المغرب',
    region: 'ar',
    latitude: 34.0181,
    longitude: -5.0078,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Casablanca',
  ),
  // السودان
  AppCity(
    name: 'الخرطوم',
    country: 'السودان',
    region: 'ar',
    latitude: 15.5007,
    longitude: 32.5599,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Khartoum',
  ),
  // موريتانيا
  AppCity(
    name: 'نواكشوط',
    country: 'موريتانيا',
    region: 'ar',
    latitude: 18.0735,
    longitude: -15.9582,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Nouakchott',
  ),
  // الصومال
  AppCity(
    name: 'مقديشو',
    country: 'الصومال',
    region: 'ar',
    latitude: 2.0469,
    longitude: 45.3182,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Mogadishu',
  ),
  // جيبوتي
  AppCity(
    name: 'جيبوتي',
    country: 'جيبوتي',
    region: 'ar',
    latitude: 11.8251,
    longitude: 42.5903,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Djibouti',
  ),

  // ---------- آسيا ----------
  AppCity(
    name: 'إسطنبول',
    country: 'تركيا',
    region: 'asia',
    latitude: 41.0082,
    longitude: 28.9784,
    method: CalculationMethod.turkiye,
    timezone: 'Europe/Istanbul',
  ),
  AppCity(
    name: 'أنقرة',
    country: 'تركيا',
    region: 'asia',
    latitude: 39.9334,
    longitude: 32.8597,
    method: CalculationMethod.turkiye,
    timezone: 'Europe/Istanbul',
  ),
  AppCity(
    name: 'طهران',
    country: 'إيران',
    region: 'asia',
    latitude: 35.6892,
    longitude: 51.389,
    method: CalculationMethod.tehran,
    timezone: 'Asia/Tehran',
  ),
  AppCity(
    name: 'مشهد',
    country: 'إيران',
    region: 'asia',
    latitude: 36.2605,
    longitude: 59.6168,
    method: CalculationMethod.tehran,
    timezone: 'Asia/Tehran',
  ),
  AppCity(
    name: 'كراتشي',
    country: 'باكستان',
    region: 'asia',
    latitude: 24.8607,
    longitude: 67.0011,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Karachi',
  ),
  AppCity(
    name: 'لاهور',
    country: 'باكستان',
    region: 'asia',
    latitude: 31.5204,
    longitude: 74.3587,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Karachi',
  ),
  AppCity(
    name: 'إسلام آباد',
    country: 'باكستان',
    region: 'asia',
    latitude: 33.6844,
    longitude: 73.0479,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Karachi',
  ),
  AppCity(
    name: 'نيودلهي',
    country: 'الهند',
    region: 'asia',
    latitude: 28.6139,
    longitude: 77.209,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Kolkata',
  ),
  AppCity(
    name: 'مومباي',
    country: 'الهند',
    region: 'asia',
    latitude: 19.076,
    longitude: 72.8777,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Kolkata',
  ),
  AppCity(
    name: 'حيدر أباد',
    country: 'الهند',
    region: 'asia',
    latitude: 17.385,
    longitude: 78.4867,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Kolkata',
  ),
  AppCity(
    name: 'دكا',
    country: 'بنغلاديش',
    region: 'asia',
    latitude: 23.8103,
    longitude: 90.4125,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Dhaka',
  ),
  AppCity(
    name: 'جاكرتا',
    country: 'إندونيسيا',
    region: 'asia',
    latitude: -6.2088,
    longitude: 106.8456,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Jakarta',
  ),
  AppCity(
    name: 'باندونغ',
    country: 'إندونيسيا',
    region: 'asia',
    latitude: -6.9175,
    longitude: 107.6191,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Jakarta',
  ),
  AppCity(
    name: 'سورابايا',
    country: 'إندونيسيا',
    region: 'asia',
    latitude: -7.2575,
    longitude: 112.7521,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Jakarta',
  ),
  AppCity(
    name: 'كوالالمبور',
    country: 'ماليزيا',
    region: 'asia',
    latitude: 3.139,
    longitude: 101.6869,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Kuala_Lumpur',
  ),
  AppCity(
    name: 'سنغافورة',
    country: 'سنغافورة',
    region: 'asia',
    latitude: 1.3521,
    longitude: 103.8198,
    method: CalculationMethod.singapore,
    timezone: 'Asia/Singapore',
  ),
  AppCity(
    name: 'بانكوك',
    country: 'تايلاند',
    region: 'asia',
    latitude: 13.7563,
    longitude: 100.5018,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Bangkok',
  ),
  AppCity(
    name: 'مانيلا',
    country: 'الفلبين',
    region: 'asia',
    latitude: 14.5995,
    longitude: 120.9842,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Manila',
  ),
  AppCity(
    name: 'طوكيو',
    country: 'اليابان',
    region: 'asia',
    latitude: 35.6762,
    longitude: 139.6503,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Tokyo',
  ),
  AppCity(
    name: 'أوساكا',
    country: 'اليابان',
    region: 'asia',
    latitude: 34.6937,
    longitude: 135.5023,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Tokyo',
  ),
  AppCity(
    name: 'سيول',
    country: 'كوريا الجنوبية',
    region: 'asia',
    latitude: 37.5665,
    longitude: 126.978,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Seoul',
  ),
  AppCity(
    name: 'بكين',
    country: 'الصين',
    region: 'asia',
    latitude: 39.9042,
    longitude: 116.4074,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Shanghai',
  ),
  AppCity(
    name: 'شنغهاي',
    country: 'الصين',
    region: 'asia',
    latitude: 31.2304,
    longitude: 121.4737,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Shanghai',
  ),
  AppCity(
    name: 'كانتون (غوانزو)',
    country: 'الصين',
    region: 'asia',
    latitude: 23.1291,
    longitude: 113.2644,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Shanghai',
  ),
  AppCity(
    name: 'هونغ كونغ',
    country: 'الصين',
    region: 'asia',
    latitude: 22.3193,
    longitude: 114.1694,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Shanghai',
  ),
  AppCity(
    name: 'ألماتي',
    country: 'كازاخستان',
    region: 'asia',
    latitude: 43.222,
    longitude: 76.8512,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Almaty',
  ),
  AppCity(
    name: 'طشقند',
    country: 'أوزبكستان',
    region: 'asia',
    latitude: 41.2995,
    longitude: 69.2401,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Asia/Tashkent',
  ),
  AppCity(
    name: 'كابول',
    country: 'أفغانستان',
    region: 'asia',
    latitude: 34.5553,
    longitude: 69.2075,
    method: CalculationMethod.karachi,
    timezone: 'Asia/Kabul',
  ),

  // ---------- أوروبا ----------
  AppCity(
    name: 'لندن',
    country: 'بريطانيا',
    region: 'europe',
    latitude: 51.5074,
    longitude: -0.1278,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/London',
  ),
  AppCity(
    name: 'مانشستر',
    country: 'بريطانيا',
    region: 'europe',
    latitude: 53.4808,
    longitude: -2.2426,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/London',
  ),
  AppCity(
    name: 'باريس',
    country: 'فرنسا',
    region: 'europe',
    latitude: 48.8566,
    longitude: 2.3522,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Paris',
  ),
  AppCity(
    name: 'مرسيليا',
    country: 'فرنسا',
    region: 'europe',
    latitude: 43.2965,
    longitude: 5.3698,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Paris',
  ),
  AppCity(
    name: 'برلين',
    country: 'ألمانيا',
    region: 'europe',
    latitude: 52.52,
    longitude: 13.405,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Berlin',
  ),
  AppCity(
    name: 'فرانكفورت',
    country: 'ألمانيا',
    region: 'europe',
    latitude: 50.1109,
    longitude: 8.6821,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Berlin',
  ),
  AppCity(
    name: 'ميونخ',
    country: 'ألمانيا',
    region: 'europe',
    latitude: 48.1351,
    longitude: 11.582,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Berlin',
  ),
  AppCity(
    name: 'كولونيا',
    country: 'ألمانيا',
    region: 'europe',
    latitude: 50.9375,
    longitude: 6.9603,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Berlin',
  ),
  AppCity(
    name: 'مدريد',
    country: 'إسبانيا',
    region: 'europe',
    latitude: 40.4168,
    longitude: -3.7038,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Madrid',
  ),
  AppCity(
    name: 'برشلونة',
    country: 'إسبانيا',
    region: 'europe',
    latitude: 41.3874,
    longitude: 2.1686,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Madrid',
  ),
  AppCity(
    name: 'إشبيلية',
    country: 'إسبانيا',
    region: 'europe',
    latitude: 37.3891,
    longitude: -5.9845,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Madrid',
  ),
  AppCity(
    name: 'غرناطة',
    country: 'إسبانيا',
    region: 'europe',
    latitude: 37.1773,
    longitude: -3.5986,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Madrid',
  ),
  AppCity(
    name: 'روما',
    country: 'إيطاليا',
    region: 'europe',
    latitude: 41.9028,
    longitude: 12.4964,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Rome',
  ),
  AppCity(
    name: 'ميلانو',
    country: 'إيطاليا',
    region: 'europe',
    latitude: 45.4642,
    longitude: 9.19,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Rome',
  ),
  AppCity(
    name: 'أمستردام',
    country: 'هولندا',
    region: 'europe',
    latitude: 52.3676,
    longitude: 4.9041,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Amsterdam',
  ),
  AppCity(
    name: 'روتردام',
    country: 'هولندا',
    region: 'europe',
    latitude: 51.9244,
    longitude: 4.4777,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Amsterdam',
  ),
  AppCity(
    name: 'بروكسل',
    country: 'بلجيكا',
    region: 'europe',
    latitude: 50.8503,
    longitude: 4.3517,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Brussels',
  ),
  AppCity(
    name: 'ستوكهولم',
    country: 'السويد',
    region: 'europe',
    latitude: 59.3293,
    longitude: 18.0686,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Stockholm',
  ),
  AppCity(
    name: 'أوسلو',
    country: 'النرويج',
    region: 'europe',
    latitude: 59.9139,
    longitude: 10.7522,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Oslo',
  ),
  AppCity(
    name: 'كوبنهاغن',
    country: 'الدنمارك',
    region: 'europe',
    latitude: 55.6761,
    longitude: 12.5683,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Copenhagen',
  ),
  AppCity(
    name: 'هلسنكي',
    country: 'فنلندا',
    region: 'europe',
    latitude: 60.1699,
    longitude: 24.9384,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Helsinki',
  ),
  AppCity(
    name: 'فينا',
    country: 'النمسا',
    region: 'europe',
    latitude: 48.2082,
    longitude: 16.3738,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Vienna',
  ),
  AppCity(
    name: 'زيوريخ',
    country: 'سويسرا',
    region: 'europe',
    latitude: 47.3769,
    longitude: 8.5417,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Zurich',
  ),
  AppCity(
    name: 'وارسو',
    country: 'بولندا',
    region: 'europe',
    latitude: 52.2297,
    longitude: 21.0122,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Warsaw',
  ),
  AppCity(
    name: 'أثينا',
    country: 'اليونان',
    region: 'europe',
    latitude: 37.9838,
    longitude: 23.7275,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Athens',
  ),
  AppCity(
    name: 'موسكو',
    country: 'روسيا',
    region: 'europe',
    latitude: 55.7558,
    longitude: 37.6173,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Moscow',
  ),
  AppCity(
    name: 'دبلن',
    country: 'أيرلندا',
    region: 'europe',
    latitude: 53.3498,
    longitude: -6.2603,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Europe/Dublin',
  ),

  // ---------- أفريقيا ----------
  AppCity(
    name: 'نيروبي',
    country: 'كينيا',
    region: 'africa',
    latitude: -1.2921,
    longitude: 36.8219,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Nairobi',
  ),
  AppCity(
    name: 'أديس أبابا',
    country: 'إثيوبيا',
    region: 'africa',
    latitude: 9.03,
    longitude: 38.74,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Addis_Ababa',
  ),
  AppCity(
    name: 'لاغوس',
    country: 'نيجيريا',
    region: 'africa',
    latitude: 6.5244,
    longitude: 3.3792,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Lagos',
  ),
  AppCity(
    name: 'أبوجا',
    country: 'نيجيريا',
    region: 'africa',
    latitude: 9.0765,
    longitude: 7.3986,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Lagos',
  ),
  AppCity(
    name: 'دكار',
    country: 'السنغال',
    region: 'africa',
    latitude: 14.7167,
    longitude: -17.4677,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Dakar',
  ),
  AppCity(
    name: 'أبيدجان',
    country: 'ساحل العاج',
    region: 'africa',
    latitude: 5.3599,
    longitude: -4.0083,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Abidjan',
  ),
  AppCity(
    name: 'أكرا',
    country: 'غانا',
    region: 'africa',
    latitude: 5.6037,
    longitude: -0.187,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Accra',
  ),
  AppCity(
    name: 'كيجالي',
    country: 'رواندا',
    region: 'africa',
    latitude: -1.9441,
    longitude: 30.0619,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Kigali',
  ),
  AppCity(
    name: 'جوهانسبرغ',
    country: 'جنوب أفريقيا',
    region: 'africa',
    latitude: -26.2041,
    longitude: 28.0473,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Johannesburg',
  ),
  AppCity(
    name: 'كيب تاون',
    country: 'جنوب أفريقيا',
    region: 'africa',
    latitude: -33.9249,
    longitude: 18.4241,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Africa/Johannesburg',
  ),

  // ---------- الأمريكتان ----------
  AppCity(
    name: 'نيويورك',
    country: 'الولايات المتحدة',
    region: 'americas',
    latitude: 40.7128,
    longitude: -74.006,
    method: CalculationMethod.northAmerica,
    timezone: 'America/New_York',
  ),
  AppCity(
    name: 'شيكاغو',
    country: 'الولايات المتحدة',
    region: 'americas',
    latitude: 41.8781,
    longitude: -87.6298,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Chicago',
  ),
  AppCity(
    name: 'لوس أنجلوس',
    country: 'الولايات المتحدة',
    region: 'americas',
    latitude: 34.0522,
    longitude: -118.2437,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Los_Angeles',
  ),
  AppCity(
    name: 'هيوستن',
    country: 'الولايات المتحدة',
    region: 'americas',
    latitude: 29.7604,
    longitude: -95.3698,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Chicago',
  ),
  AppCity(
    name: 'ديترويت',
    country: 'الولايات المتحدة',
    region: 'americas',
    latitude: 42.3314,
    longitude: -83.0458,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Detroit',
  ),
  AppCity(
    name: 'ديربورن',
    country: 'الولايات المتحدة',
    region: 'americas',
    latitude: 42.3223,
    longitude: -83.1763,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Detroit',
  ),
  AppCity(
    name: 'تورونتو',
    country: 'كندا',
    region: 'americas',
    latitude: 43.6532,
    longitude: -79.3832,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Toronto',
  ),
  AppCity(
    name: 'مونتريال',
    country: 'كندا',
    region: 'americas',
    latitude: 45.5017,
    longitude: -73.5673,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Toronto',
  ),
  AppCity(
    name: 'فانكوفر',
    country: 'كندا',
    region: 'americas',
    latitude: 49.2827,
    longitude: -123.1207,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Vancouver',
  ),
  AppCity(
    name: 'أوتاوا',
    country: 'كندا',
    region: 'americas',
    latitude: 45.4215,
    longitude: -75.6972,
    method: CalculationMethod.northAmerica,
    timezone: 'America/Toronto',
  ),
  AppCity(
    name: 'مكسيكو سيتي',
    country: 'المكسيك',
    region: 'americas',
    latitude: 19.4326,
    longitude: -99.1332,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'America/Mexico_City',
  ),
  AppCity(
    name: 'ساو باولو',
    country: 'البرازيل',
    region: 'americas',
    latitude: -23.5505,
    longitude: -46.6333,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'America/Sao_Paulo',
  ),
  AppCity(
    name: 'ريو دي جانيرو',
    country: 'البرازيل',
    region: 'americas',
    latitude: -22.9068,
    longitude: -43.1729,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'America/Sao_Paulo',
  ),
  AppCity(
    name: 'بوينس آيرس',
    country: 'الأرجنتين',
    region: 'americas',
    latitude: -34.6037,
    longitude: -58.3816,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'America/Argentina/Buenos_Aires',
  ),

  // ---------- أوقيانوسيا ----------
  AppCity(
    name: 'سيدني',
    country: 'أستراليا',
    region: 'oceania',
    latitude: -33.8688,
    longitude: 151.2093,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Australia/Sydney',
  ),
  AppCity(
    name: 'ملبورن',
    country: 'أستراليا',
    region: 'oceania',
    latitude: -37.8136,
    longitude: 144.9631,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Australia/Melbourne',
  ),
  AppCity(
    name: 'بريسبان',
    country: 'أستراليا',
    region: 'oceania',
    latitude: -27.4698,
    longitude: 153.0251,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Australia/Brisbane',
  ),
  AppCity(
    name: 'أوكلاند',
    country: 'نيوزيلندا',
    region: 'oceania',
    latitude: -36.8485,
    longitude: 174.7633,
    method: CalculationMethod.muslimWorldLeague,
    timezone: 'Pacific/Auckland',
  ),
];
